# Generated by Django 3.2.4 on 2021-06-17 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedSystemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(default='', max_length=250)),
                ('details', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='SystemPorts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ports', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='SystemScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.DateTimeField(blank=True, null=True)),
                ('ports', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='systems.systemports')),
            ],
        ),
        migrations.CreateModel(
            name='ManagedSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_name', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='systems.systemscan')),
                ('sys_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='systems.managedsystemtype')),
            ],
        ),
    ]
