# Generated by Django 3.2.4 on 2021-06-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedsystem',
            name='sys_location',
            field=models.JSONField(default=dict),
        ),
    ]
