# Generated by Django 3.2.4 on 2021-06-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0002_managedsystem_sys_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedsystem',
            name='sys_ip',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='managedsystem',
            name='sys_location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
