# Generated by Django 3.2.4 on 2021-06-17 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0003_auto_20210617_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managedsystem',
            name='details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='systems.systemscan'),
        ),
        migrations.AlterField(
            model_name='managedsystem',
            name='sys_ip',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='managedsystem',
            name='sys_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='systems.managedsystemtype'),
        ),
    ]
