# Generated by Django 3.2.4 on 2021-06-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0005_alter_systemports_ports'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemports',
            name='sys_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='systemscan',
            name='sys_name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
