# Generated by Django 3.2.4 on 2021-06-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0006_auto_20210617_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemscan',
            name='sys_name',
            field=models.CharField(max_length=250),
        ),
    ]
