# Generated by Django 3.2.4 on 2021-06-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0008_auto_20210617_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managedsystem',
            name='sys_location',
            field=models.URLField(default='', max_length=100),
        ),
    ]
