# Generated by Django 3.2.4 on 2021-06-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0010_auto_20210617_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemports',
            name='ports',
        ),
        migrations.AddField(
            model_name='systemports',
            name='errors',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='systemports',
            name='ports_to_scan',
            field=models.CharField(default='22-80', max_length=20),
        ),
        migrations.AddField(
            model_name='systemports',
            name='scan_results',
            field=models.JSONField(default=dict),
        ),
    ]
