# Generated by Django 3.2.4 on 2021-06-18 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0012_auto_20210618_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedsystem',
            name='is_scanning',
            field=models.BooleanField(default=False),
        ),
    ]
