# Generated by Django 3.2.4 on 2021-06-18 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0013_managedsystem_is_scanning'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemscan',
            name='headers',
            field=models.JSONField(default=dict),
        ),
    ]
