# Generated by Django 3.2.4 on 2021-06-18 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0014_systemscan_headers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemscan',
            old_name='ports_to_scan',
            new_name='ports_scanned',
        ),
    ]
