# Generated by Django 3.2.4 on 2021-06-18 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0015_rename_ports_to_scan_systemscan_ports_scanned'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemscan',
            name='whois',
            field=models.JSONField(default=dict),
        ),
    ]
