# Generated by Django 3.2.4 on 2021-06-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0016_systemscan_whois'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemscan',
            name='subdomains',
            field=models.JSONField(default=dict),
        ),
    ]
