# Generated by Django 3.2.4 on 2021-06-18 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0017_systemscan_subdomains'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managedsystem',
            name='sys_scans',
        ),
    ]
