# Generated by Django 3.2.4 on 2021-06-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0018_remove_managedsystem_sys_scans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managedsystem',
            name='sys_location',
            field=models.URLField(blank=True, default='', max_length=100, null=True),
        ),
    ]
