# Generated by Django 3.2.4 on 2021-06-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0019_alter_managedsystem_sys_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemscan',
            name='subdomains',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
